export interface WidgetNode {
  id: string;
  name: string;
  type: 'framework' | 'layout' | 'component' | 'navigation' | 'input';
  screen: 1 | 2 | 'both';
  description: string;
  properties: string[];
  keyConcept: string;
  children?: WidgetNode[];
}

export const widgetHierarchy: WidgetNode = {
  id: "app",
  name: "MaterialApp",
  type: "framework",
  screen: "both",
  description: "The top-level container defining Material Design themes, routes, and localization.",
  properties: ["theme: ThemeData(useMaterial3: true)", "home: StudentProfileScreen()"],
  keyConcept: "Configures the Navigator and global theme for the entire app.",
  children: [
    {
      id: "navigator",
      name: "Navigator",
      type: "navigation",
      screen: "both",
      description: "Manages a stack of Route objects. Screen 1 pushes Screen 2 onto this stack.",
      properties: ["Navigator.push<String>()", "Navigator.pop(context, result)"],
      keyConcept: "LIFO navigation stack where pages are pushed and popped with optional data payloads.",
      children: [
        {
          id: "screen1_scaffold",
          name: "Scaffold (Screen 1)",
          type: "layout",
          screen: 1,
          description: "Implements the basic Material Design visual layout structure for Screen 1.",
          properties: ["appBar", "body: Center(...)"],
          keyConcept: "Provides slots for app bars, drawers, floating action buttons, and body content.",
          children: [
            {
              id: "screen1_appbar",
              name: "AppBar",
              type: "component",
              screen: 1,
              description: "A Material Design app bar displaying the screen title 'Student Profile'.",
              properties: ["title: Text('Student Profile')", "centerTitle: true", "elevation: 2"],
              keyConcept: "Consistent top branding and screen action bar.",
            },
            {
              id: "screen1_column",
              name: "Column",
              type: "layout",
              screen: 1,
              description: "A widget that displays its children in a vertical array.",
              properties: ["mainAxisAlignment: Center", "crossAxisAlignment: Center"],
              keyConcept: "Primary vertical flex layout in Flutter.",
              children: [
                {
                  id: "circle_avatar",
                  name: "CircleAvatar",
                  type: "component",
                  screen: 1,
                  description: "A circle that represents a user profile image or initials.",
                  properties: ["radius: 64", "backgroundImage: NetworkImage(...)"],
                  keyConcept: "Built-in Material widget for circular avatars.",
                },
                {
                  id: "text_name",
                  name: "Text (Student Name)",
                  type: "component",
                  screen: 1,
                  description: "Displays the dynamic student name string with headline styling.",
                  properties: ["style: headlineMedium", "textAlign: TextAlign.center"],
                  keyConcept: "Re-renders when setState() is called after receiving data from Screen 2.",
                },
                {
                  id: "text_course",
                  name: "Text (Student Course)",
                  type: "component",
                  screen: 1,
                  description: "Displays the enrolled academic program or degree.",
                  properties: ["style: titleMedium", "color: primary"],
                  keyConcept: "Provides supplementary student metadata.",
                },
                {
                  id: "screen1_btn",
                  name: "ElevatedButton",
                  type: "component",
                  screen: 1,
                  description: "Button that initiates navigation to Screen 2 using Navigator.push.",
                  properties: ["onPressed: _navigateToEditScreen", "label: Text('Edit Student Name')"],
                  keyConcept: "Awaits the Future returned by Navigator.push to receive the updated name.",
                },
              ],
            },
          ],
        },
        {
          id: "screen2_scaffold",
          name: "Scaffold (Screen 2)",
          type: "layout",
          screen: 2,
          description: "Top layout container for the Edit Student Name screen.",
          properties: ["appBar: AppBar(title: Text('Edit Profile'))", "body: Form(...)"],
          keyConcept: "Hosts form controls and navigation back button in the AppBar.",
          children: [
            {
              id: "screen2_appbar",
              name: "AppBar (with BackButton)",
              type: "component",
              screen: 2,
              description: "AppBar with automatic BackButton generated by Navigator.",
              properties: ["title: Text('Edit Profile')", "automaticallyImplyLeading: true"],
              keyConcept: "Flutter automatically displays a back arrow when a route is pushed.",
            },
            {
              id: "screen2_column",
              name: "Column (Form)",
              type: "layout",
              screen: 2,
              description: "Vertical layout holding instruction text, TextField, and action buttons.",
              properties: ["crossAxisAlignment: Stretch"],
              keyConcept: "Stretches form controls across full screen width.",
              children: [
                {
                  id: "text_field",
                  name: "TextField / TextFormField",
                  type: "input",
                  screen: 2,
                  description: "Allows the user to edit the student's name.",
                  properties: ["controller: _nameController", "decoration: InputDecoration(...)"],
                  keyConcept: "Controlled via TextEditingController to read input text on save.",
                },
                {
                  id: "screen2_btn",
                  name: "ElevatedButton (Save)",
                  type: "component",
                  screen: 2,
                  description: "Validates input and calls Navigator.pop(context, updatedName).",
                  properties: ["onPressed: _saveAndReturn", "child: Text('Save Changes')"],
                  keyConcept: "Pops Screen 2 off the stack and yields the result back to Screen 1.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
